version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: tipsterchat
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: tipsterchat
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: mepass
      ME_CONFIG_MONGODB_PORT: 27017
      DATABASE_PROD: tips_prod
      DATABASE_TEST: tips_test

  tips-app:
    build:
      context: ./src
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      MONGODB_CONNSTRING: mongodb://root:tipsterchat@172.18.0.2:27017
      MONGODB_URI: mongodb://localhost:27017
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    links:
      - mongo
